---
# Jenkins installation tasks

- name: Check if Jenkins is installed
  command: dpkg-query -W -f='${Status}' jenkins
  register: jenkins_check
  failed_when: false
  changed_when: false

- name: Display Jenkins status
  debug:
    msg: "Jenkins is already installed"
  when: "'installed' in jenkins_check.stdout"

- name: Add Jenkins apt key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  when: "not ('installed' in jenkins_check.stdout)"

- name: Add Jenkins repository
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins
  when: "not ('installed' in jenkins_check.stdout)"

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes
  when: "not ('installed' in jenkins_check.stdout)"

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes
  when: "not ('installed' in jenkins_check.stdout)"

- name: Ensure Jenkins is running
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Get Jenkins initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_admin_password
  failed_when: false
  changed_when: false
  when: "not ('installed' in jenkins_check.stdout)"

- name: Display Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_admin_password.stdout }}"
  when: "not ('installed' in jenkins_check.stdout) and jenkins_admin_password.stdout is defined"

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: 200
    timeout: 15
  register: jenkins_service_status
  retries: 10
  delay: 5
  until: jenkins_service_status.status == 200
  changed_when: false
  failed_when: false
  when: "not ('installed' in jenkins_check.stdout)"

- name: Display Jenkins URL
  debug:
    msg: "Jenkins is available at: http://{{ ansible_host }}:8080" 