---
# Node.js installation tasks

- name: Check if Node.js is installed
  command: which node
  register: node_check
  failed_when: false
  changed_when: false

- name: Check Node.js version
  shell: node -v | grep -o 'v[0-9]*'
  register: node_version_output
  failed_when: false
  changed_when: false
  when: node_check.rc == 0

- name: Display Node.js status
  debug:
    msg: "Node.js {{ node_version_output.stdout }} is already installed"
  when: node_check.rc == 0 and node_version_output is defined and node_version_output.stdout | default('') | regex_search('v' + node_version)

- name: Check if nodemon is installed
  command: which nodemon
  register: nodemon_check
  failed_when: false
  changed_when: false

- name: Display nodemon status
  debug:
    msg: "nodemon is already installed"
  when: nodemon_check.rc == 0

- name: Install Node.js prerequisites
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes
  when: node_check.rc != 0 or (node_version_output is defined and not node_version_output.stdout | default('') | regex_search('v' + node_version))

- name: Add Node.js repository key
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  args:
    creates: /etc/apt/keyrings/nodesource.gpg
  when: node_check.rc != 0 or (node_version_output is defined and not node_version_output.stdout | default('') | regex_search('v' + node_version))

- name: Add Node.js {{ node_version }} repository
  shell: |
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
  when: node_check.rc != 0 or (node_version_output is defined and not node_version_output.stdout | default('') | regex_search('v' + node_version))

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes
  when: node_check.rc != 0 or (node_version_output is defined and not node_version_output.stdout | default('') | regex_search('v' + node_version))

- name: Install nodemon globally
  npm:
    name: nodemon
    global: yes
    state: present
  when: nodemon_check.rc != 0 